### ISSUE TITLE
Can't start instance

### ISSUE THREAD

**Issue by cimba007** [iobroker-community-adapters/ioBroker.samsung-community#12]
Installed 0.2.9 from github and it does not start

Platform: linux
RAM: 969.6 MB
Node.js: v8.14.0
NPM: 6.4.1

startInstance samsung-community.0: cannot find start file!

**Comment by Apollon77** [comment]
Please execute manually 

iobroker upload samsung-community

**Comment by cimba007** [comment]
Thank you for your fast response. Still the same unfortunatly:


host.ioBroker-RasPi | 2019-06-08 22:48:48.011 | error | startInstance samsung-community.0: cannot find start file!
-- | -- | -- | --
host.ioBroker-RasPi | 2019-06-08 22:48:48.008 | info | object change system.adapter.samsung-community.0

pi@ioBroker-RasPi:~ $ iobroker upload samsung-community
got /opt/iobroker/node_modules/iobroker.samsung-community/admin
upload [1] samsung-community.admin /opt/iobroker/node_modules/iobroker.samsung-community/admin/samsung.png samsung.png image/png
upload [0] samsung-community.admin /opt/iobroker/node_modules/iobroker.samsung-community/admin/index.html index.html text/html
pi@ioBroker-RasPi:~ $

**Comment by kugelkopf123** [comment]
I have the same problem.

**Comment by Apollon77** [comment]
Please update from githbu and try again

**Comment by kugelkopf123** [comment]
> Please update from githbu and try again

Thanks! Now it works!
