### ISSUE TITLE
Error: Cannot find module 'node-ssdp' wenn Discovery Adapter nicht installiert ist

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.samsung-community#44]
Ich hab vor kurzem meine Adapterlandschaft etwas aufgeräumt und unter anderem den Adapter discovery/Gerätesuche gelöscht.

Einige Zeit später hab ich im Log die unten stehenden Errors vom "Samsung TV Adapter (Community)" gefunden und es hat etwas gedauert bis ich die Abhängigkeit zum Discovery(Gerätesuche) Adapter gefunden habe. Sobald ich den Discovery Adapter wieder installiere gibt es vom samsung-community Adapter keine Errors mehr.

Ist es notwendig, dass es diese harte Abhängigkeit zum Discovery Adapter gibt?

Samsung TV Adapter (Community): v0.4.0
Adapter discovery/Gerätesuche 2.6.1 (2021-02-28)

Meine System:
AdapterVersion: js-controller: 3.2.16
node: 12.21.0 
nodejs: v12.21.0
npm: 6.14.11 
Admin: 4.2.1 
Java Script Enging: 5.0.9

`
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.273 | info | Restart adapter system.adapter.samsung-community.0 because enabled
-- | -- | -- | --
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.272 | error | instance system.adapter.samsung-community.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.271 | error | Caught by controller[0]: }
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.270 | error | Caught by controller[0]:   ]
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.269 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.samsung-community/main.js'
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.268 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.samsung-community/lib/samsungtv/build/device.js',
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.268 | error | Caught by controller[0]:   requireStack: [
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.267 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.266 | error | Caught by controller[0]:     at internal/main/run_main_module.js:17:47 {
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.265 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.264 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.263 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.262 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.261 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.260 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.samsung-community/main.js:6:17)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.259 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.258 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.257 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.256 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.256 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.255 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.254 | error | Caught by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/iobroker.samsung-community/lib/samsungtv/build/device.js:43:17)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.253 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.252 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.251 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.250 | error | Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.249 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.samsung-community/main.js
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.248 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.samsung-community/lib/samsungtv/build/device.js
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.247 | error | Caught by controller[0]: Require stack:
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.246 | error | Caught by controller[0]: Error: Cannot find module 'node-ssdp'
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.245 | error | Caught by controller[0]:   ^
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.245 | error | Caught by controller[0]:   throw err;
host.beebox(iobrokerMaster) | 2021-03-07 18:48:49.244 | error | Caught by controller[0]: internal/modules/cjs/loader.js:818
host.beebox(iobrokerMaster) | 2021-03-07 18:48:47.777 | info | instance system.adapter.samsung-community.0 started with pid 1907

`

**Comment by Apollon77** [comment]
It seems more that the adapter misses some dependencies...

**Comment by Feuer-sturm** [comment]
@Apollon77 I deleted discovery adapter and after this I installed node-ssdp by using the following way:
```
proxmox@ioBrokerBETA:~$ cd /opt/iobroker/
proxmox@ioBrokerBETA:/opt/iobroker$ npm install node-ssdp
[sudo] password for proxmox: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ node-ssdp@4.0.1
added 3 packages from 4 contributors in 25.676s

33 packages are looking for funding
  run `npm fund` for details
```

After this samsung instance is able to start without throwing any errors..

**Comment by Grothesk242** [comment]
Ich habe gerade heute frisch installiert, die node-ssdp kommt aber jetzt als dependency mit: 

```
echad@chet:/opt/iobroker $ npm list node-ssdp
iobroker.inst@3.0.0 /opt/iobroker
└─┬ iobroker.samsung-community@0.5.0 (git+ssh://git@github.com/iobroker-community-adapters/ioBroker.samsung-community.git#ea8f9f373f38d733e3d1a848e5aecf44e66bf34d)
  └─┬ samsungtv@0.0.0 (git+ssh://git@github.com/luca-saggese/samsungtv.git#7fc20107455414e2afb94022682e0787e8635550)
    └── node-ssdp@2.9.1

```

Kann also geschlossen werden.
