### ISSUE TITLE
Please extend functionality to H and J series from 2014 +2015, library available :-) !!!

### ISSUE THREAD

**Issue by mwp007** [iobroker-community-adapters/ioBroker.samsung-community#45]
I have succesfully tested this JS [library](https://github.com/tdudek/samsung-remote-models-2014-and-newer).

Please implement this library into the adapter.

**Comment by mwp007** [comment]
@jogibear9988 vielleicht bist du so nett? :-)

**Comment by mwp007** [comment]
hab mich vorerst selber dran gesetzt und geforked.. gott habe ich lag nicht mehr programmiert

**Comment by Apollon77** [comment]
Cool, freuen uns über jeden PR!! Danke

**Comment by mwp007** [comment]
ok done
https://github.com/mwp007/ioBroker.samsung-community
