### ISSUE TITLE
Confirm the new connection dialog does not show up on my MU65 Sammlung TV

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.samsung-community#6]
_From @tippmam on February 18, 2018 5:50_

Hey, installed your Adapter within my ioBroker Installation which is running on a Synology NAS via Docker. After the Installation the Adapter discovered my TV's IP and i can see the TV's Objects. I'm not able to send any command to my TV or get any "live" Information. I think this is, because the "confirm dialog" did not come up on my TV like it should, after I installed the Adapter.  

- I tried to reinstall the Adapter serval times
- My TV is connected via WLAN

Kind Regards,
Michael

_Copied from original issue: soef/ioBroker.samsung#17_

**Comment by jogibear9988** [comment]
_From @C4b4nossi on May 13, 2018 20:52_

I have the same problem: the Dialog to confirm the new connection does NOT show up on the TV (UE55H6470SS) - is this related to the protocol or the TV itself?

TV is connected with WLAN; I have only 2 Devices in the connection lists of the TV and deleted all other old connections

**Comment by HabibA007** [comment]
Same issue at my installation. Samsung  JS9090 from 2015 and it's connected with cable LAN
