### ISSUE TITLE
Add Support for Compact mode (js-Controller 2.0 Feature)

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.samsung-community#9]
_From @ldittmar81 on January 20, 2019 17:57_

The upcoming version 2.0.0 of js-controller will support a new mode for low memory devices. For this, a few minor adjustments to the adapter must be made. Please follow these instructions: https://forum.iobroker.net/viewtopic.php?f=24&t=20387#p213466

_Copied from original issue: soef/ioBroker.samsung#21_

**Comment by jogibear9988** [comment]
_From @kxn25 on January 30, 2019 16:2_

Werden dann auch andere Samsung TV geräte wieder gehen?
Mein MU reagiert nicht mehr seit einem Firmware Update!
Und Einschalten ging noch nie! komischer weise funtioniert die Android App von Samsung TV Remote prima.

**Comment by Silli-Singen** [comment]
Funktioniert wohl mit den Modellen ab 2018 nicht. Der 75Q6Fn QLED - TEV wird gar nicht angesprochen.

**Comment by jogibear9988** [comment]
@Silli-Singen sollte nun gehen. ich hab nen neuen modus eingebaut (api "samsungtv")
